export const roster = [
    'Mario',
    'Luigi',
    'Peach',
    'Bowser',
    'Dr. Mario',
    'Rosalina & Luma',
    'Bowser Jr.',
    'Yoshi',
    'Donkey Kong',
    'Diddy Kong',
    'Link',
    'Zelda',
    'Sheik',
    'Young Link',
    'Ganondorf',
    'Toon Link',
    'Samus',
    'Zero Suit Samus',
    'Kirby',
    'Meta Knight',
    'King Dedede',
    'Fox',
    'Falco',
    'Wolf',
    'Pikachu',
    'Jigglypuff',
    'Pichu',
    'Mewtwo',
    'Pokemon Trainer',
    'Lucario',
    'Greninja',
    'Captain Falcon',
    'Ness',
    'Lucas',
    'Ice Climbers',
    'Marth',
    'Roy',
    'Ike',
    'Lucina',
    'Robin',
    'Corrin',
    'Mr. Game & Watch',
    'Pit',
    'Palutena',
    'Dark Pit',
    'Wario',
    'Olimar',
    'R.O.B.',
    'Villager',
    'Wii Fit Trainer',
    'Little Mac',
    'Shulk',
    'Duck Hunt',
    'Snake',
    'Sonic',
    'Mega Man',
    'Pac-Man',
    'Ryu',
    'Cloud',
    'Bayonetta',
    'Mii Brawler',
    'Mii Swordfighter',
    'Mii Gunner',
    'Daisy',
    'Piranha Plant',
    'King K. Rool',
    'Ridley',
    'Dark Samus',
    'Incineroar',
    'Chrom',
    'Byleth',
    'Isabelle',
    'Inkling',
    'Ken',
    'Simon',
    'Richter',
    'Joker',
    'Hero',
    'Banjo & Kazooie',
    'Terry',
] as const;
